fix: default org only token url
Telefonica/puppet-github-actions-runner pull request #26
Opened 2021-09-15 17:01 UTC by pdemonaco

# Summary

The default path for the API to retrieve the runner token was calculated incorrectly including 'repos' instead of 'orgs' which causes the token retrieval to fail.

I'm guessing at some point github changed their API from https://api.github.com/**repos**/$org_name/ to https://api.github.com/**orgs**/$org_name/ which broke the behavior of the token_url when no repo is specified.

# Fix Details

* Changes the token_url calculation logic in the `instance` defined type to correctly use **orgs** when no github.com api string override is provided.
* Adds some quick and dirty test code to make sure the creation script is built as expected.

2021-09-23 09:00 UTC, oscarsj approved these changes

2021-09-23 09:01 UTC, oscarsj commented on spec/classes/github_actions_runner_spec.rb
> +        end
```suggestion
        end

```

2021-09-23 12:19 UTC, mrodm requested changes
Thanks for this contribution @pdemonaco !

Just some minor changes for this PR

2021-09-25 03:38 UTC, pdemonaco commented on manifests/instance.pp
>        $url = "${github_domain}/${org_name}"
Yeah, I noticed that too - I was rushing through to get my code working for a production use case so I initially took the "quick and dirty" approach.

2021-11-05 10:02 UTC, mrodm commented
Closing this PR in favor of #32

2021-11-05 10:02 UTC, closed without merging